package com.example.demo.config;

public enum ApplicationReviewStates {
    START, PEER_REVIEW, PRINCIPAL_REVIEW,APPROVED_INITIAL, APPROVED, REJECTED_INITIAL, REJECTED, END, PRINCIPAL_REVIEW_FORK, END2
}
